[controller]
file = "waypoint_controller.py"

[deploy]
check_drone_start_pos = false
check_race_track = false
real_track_objects = false
[[deploy.drones]]
id = 1
channel = 100
drone_model = "cf21B_500"

[env]
control_mode = "attitude"
freq = 100
id = "DroneRacing-v0"
max_episode_steps = 800
seed = "random"
sensor_range = 0.7

[sim]
attitude_freq = 500
camera_view = [ 5.0, 180.0, -25.0, 0.0, 0.0, 0.0,]
drone_model = "cf21B_500"
freq = 500
physics = "so_rpy_rotor_drag"

[train]
clip_eps = 0.2
ent_coef = 0.005
gamma = 0.99
lambda_ = 0.95
lr = 0.0003
max_grad_norm = 0.5
num_envs = 128
num_epochs = 4
num_iterations = 3000
num_minibatches = 8
num_steps = 192
vf_coef = 0.5

[env.reset]
bank_path = "artifacts/low-cen-gate/reset_bank.npz"
bank_prob = 1.0
gate_indices = [ 0, 1, 2, 3,]
gate_probs = [ 0.45, 0.3, 0.17, 0.08,]
post_prev_distance_max = 0.95
post_prev_distance_min = 0.35
post_prev_prob = 0.7
post_prev_speed_max = 3.0
post_prev_speed_min = 1.5
pre_gate_speed = 0.0
yaw_jitter = 0.15

[env.reward]
ang_vel_penalty_scale = 0.004
crash_penalty = 5.0
gate_pass_bonus = 5.0
gate_width = 0.4
max_angular_speed = 25.0
max_linear_speed = 12.0
progress_scale = 30.0
perception_weight = 0.35
perception_distance_scale = 1.0
safety_activation_distance = 2.5
safety_weight = 1.5
vel_penalty_scale = 0.01

[env.track]
randomize = false
[[env.track.drones]]
pos = [ -1.5, 0.75, 0.01,]
rpy = [ 0.0, 0.0, 0.0,]
vel = [ 0, 0, 0,]
ang_vel = [ 0, 0, 0,]

[[env.track.gates]]
pos = [ 1.75, 0.15, 0.7,]
rpy = [ 0.0, 0.0, -1.1,]

[[env.track.gates]]
pos = [ 0.7, -1.3, 0.7,]
rpy = [ 0.0, 0.0, -2.67,]

[[env.track.gates]]
pos = [ -1.0, -1.05, 0.7,]
rpy = [ 0.0, 0.0, -4.24,]

[[env.track.gates]]
pos = [ -0.5, 0.75, 0.7,]
rpy = [ 0.0, 0.0, -5.81,]

[[env.track.obstacles]]
pos = [ 2.4, 1.4, 1.55,]

[env.disturbances.action]
fn = "normal"
scale = 0.0

[env.disturbances.dynamics]
fn = "uniform"

[env.randomizations.drone_inertia]
fn = "uniform"

[env.randomizations.drone_mass]
fn = "uniform"

[env.randomizations.drone_pos]
fn = "uniform"

[env.randomizations.drone_rpy]
fn = "uniform"

[env.track.safety_limits]
pos_limit_high = [ 2.5, 1.5, 2.0,]
pos_limit_low = [ -2.5, -1.5, -0.001,]

[env.disturbances.dynamics.kwargs]
maxval = [ 0.0, 0.0, 0.0,]
minval = [ 0.0, 0.0, 0.0,]

[env.randomizations.drone_inertia.kwargs]
maxval = [ 1e-6, 1e-6, 1e-6,]
minval = [ -1e-6, -1e-6, -1e-6,]

[env.randomizations.drone_mass.kwargs]
maxval = 0.005
minval = -0.005

[env.randomizations.drone_pos.kwargs]
maxval = [ 0.1, 0.1, 0.02,]
minval = [ -0.1, -0.1, 0.0,]

[env.randomizations.drone_rpy.kwargs]
maxval = [ 0.1, 0.1, 0.1,]
minval = [ -0.1, -0.1, -0.1,]
